NHSDigital/gp-connect-access-record-fhir-api

manifest_template.yml

AMB-976 message to test the pipeline

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
manifest_template.yml

AMB-976 release to internal dev and int env

---

azure/project.yml

AMB-976 changing service_base_path

---

postman/gp_connect_collection.json

AMB-980 Add PDS GET Patient Postman collection

---

manifest_template.yml

Add nhs-login scopes to products

AMB-977 Add nhs-login scopes to product

---

Makefile
ecs-proxies-containers.yml
ecs-proxies-deploy.yml
mediation_service/Dockerfile
mediation_service/Makefile
mediation_service/mediation/main.py
mediation_service/poetry.lock
mediation_service/poetry.toml
mediation_service/pyproject.toml
package-lock.json
proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml
sandbox/package-lock.json

AMB-980 Get Patient from PDS

---

mediation_service/mediation/main.py
proxies/live/apiproxy/targets/target.xml

AMB-980 update endpoint name and targets

---

postman/gp_connect_collection.json

AMB-983 add SDS calls for ToAsid and Gp-url

---

manifest_template.yml

Fix typo on product nhs-login P9 scope

AMB-000 fix typo on nhs-login product scope

---

azure/azure-release-pipeline.yml
manifest_template.yml
mediation_service/mediation/main.py
postman/gp_connect_collection.json
proxies/live/apiproxy/targets/target.xml

Amb 977 add integration tests

---

azure/templates/run-integration-tests.yml

AMB-977 change working directory for integration tests

---

azure/templates/run-integration-tests.yml

AMB-977 fix variable names

---

azure/templates/run-integration-tests.yml

AMB-977 add $ to environment variable

---

azure/templates/run-integration-tests.yml
tests/nhs-login-authenticator/selenium_nhs_login_authenticator.py
tests/test_api.py

AMB-977 decode base64 password

---

Makefile
ecs-proxies-deploy-internal-dev.yml
mediation_service/mediation/main.py

AMB-1003 try secrets on INT

---

ecs-proxies-deploy-internal-dev.yml
mediation_service/Dockerfile
mediation_service/mediation/main.py

AMB-1003 try private key

---

ecs-proxies-deploy.yml

AMB-1003 fix spell check

---

mediation_service/Dockerfile
mediation_service/mediation/pds_client.py
tests/Makefile
tests/test_api.py

AMB-1003 test pds response

---

ecs-proxies-containers.yml
ecs-proxies-deploy.yml

AMB-1003 rename docker container service back to mediation

---

ecs-proxies-deploy.yml

AMB-1003 add KID to list of env

---

mediation_service/mediation/main.py
mediation_service/mediation/pds_client.py

AMB-1003 add debug to see if secrets are passed

---

mediation_service/mediation/main.py

AMB-1003 add debug

---

mediation_service/mediation/main.py
tests/test_api.py

AMB-1003 add test endpoint

---

ecs-proxies-deploy.yml
mediation_service/Makefile

AMB-1003 pass envs

---

mediation_service/mediation/main.py
tests/test_api.py

Skipping AllergyIntolerence test. 
Two more endpoints to test environment vars and PDS client

Skipping AllergyIntolerence test. Two more endpoints to test

---

mediation_service/Makefile
mediation_service/mediation/main.py
tests/test_api.py

AMB-1003 add error handling

---

mediation_service/mediation/main.py
tests/test_api.py

AMB-1003 add check endpoints for Identity service and PDS

---

azure/azure-release-pipeline.yml

AMB-1003 disable tests on internal-dev on release

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/run-integration-tests.yml
ecs-proxies-deploy.yml
mediation_service/Makefile
mediation_service/mediation/client_credentials.py
mediation_service/mediation/main.py
mediation_service/mediation/pds_client.py
tests/Makefile
tests/configuration/cmd_options.py
tests/conftest.py
tests/test_api.py

Testing egress rules on AWS hosted target infra

AMB-1003 test egress rules

---

azure/azure-release-pipeline.yml

AMB-1003 fix yaml indentation

---

mediation_service/Makefile
mediation_service/mediation/getstructuredrecord_payload.json
mediation_service/mediation/main.py
mediation_service/mediation/orange_jwt.py
mediation_service/mediation/pds_client.py
mediation_service/mediation/ssp_client.py
tests/test_api.py

Amb 984 ssp get gpc.getstructuredrecord

---

Makefile
mediation_service/mediation/fhir_converter_client.py
mediation_service/mediation/main.py
mediation_service/mediation/pds_client.py
mediation_service/mediation/ssp_client.py
tests/test_api.py

* rest call to fhir-converter implemented 
* Update auth flow to share the token between different clients

Fhir converter request. update auth flow for shared services

---

Makefile
azure/azure-build-pipeline.yml
mediation_service/Makefile
mediation_service/mediation/filter_bundle.py
mediation_service/mediation/main.py
mediation_service/poetry.lock
mediation_service/pyproject.toml
mediation_service/tests/test_filter_bundle.py
tests/Makefile
tests/test_api.py

Return bundle of type searchset

Amb 1040 search set bundle

---

tests/nhs-login-authenticator/Dockerfile

AMB-1049 update chromedriver version

---

mediation_service/mediation/prepare_ssp_response.py
mediation_service/tests/test_prepare_ssp_response.py
tests/test_api.py

Update urls to R4 UKCore in Bundle and Allergy intolerance resources

update urls to R4 UKCore in Bundle and Allergy intolerance resources

---

demo_client/src/oauth-nhsd-api/Helpers/Allergy.cs
demo_client/src/oauth-nhsd-api/Pages/Allergies.cshtml
demo_client/src/oauth-nhsd-api/Pages/Allergies.cshtml.cs
demo_client/src/oauth-nhsd-api/Pages/AllergiesDataDump.cshtml
demo_client/src/oauth-nhsd-api/Pages/AllergyDetails.cshtml.cs

AMB-1064 Add data dump page + navigation using refactored parsing class

---

mediation_service/mediation/getstructuredrecord_payload.json
mediation_service/mediation/prepare_ssp_response.py
mediation_service/tests/test_prepare_ssp_response.py
tests/test_api.py

AMB-1092: Return resolved allergies

---

mediation_service/mediation/handle_resolved_allergy.py
mediation_service/mediation/main.py
mediation_service/tests/test_handle_resolved_allergy.py
tests/test_api.py

Workaround to manually add resolved clinicalStatus to allergyIntolerance resources while issue https://github.com/hapifhir/org.hl7.fhir.core/issues/792 is unresolved

Amb 1119 handle resolved allergy clinical status

---

proxies/live/apiproxy/resources/jsc/HealthCheck.SetResponse.js

AMB-1109 check response body to determine the health

---

demo_client/src/oauth-nhsd-api/Helpers/Allergy.cs
demo_client/src/oauth-nhsd-api/Pages/Allergies.cshtml
demo_client/src/oauth-nhsd-api/Pages/Allergies.cshtml.cs
demo_client/src/oauth-nhsd-api/Pages/AllergyDetails.cshtml
demo_client/src/oauth-nhsd-api/Pages/AllergyDetails.cshtml.cs
demo_client/src/oauth-nhsd-api/Pages/Error.cshtml
demo_client/src/oauth-nhsd-api/Pages/Home.cshtml
demo_client/src/oauth-nhsd-api/Pages/Index.cshtml
demo_client/src/oauth-nhsd-api/Pages/Index.cshtml.cs
demo_client/src/oauth-nhsd-api/Pages/Shared/_Layout.cshtml
demo_client/src/oauth-nhsd-api/Startup.cs
demo_client/src/oauth-nhsd-api/appsettings.json

* if demo client receives 401 token expired, get user to reauth

added redirect to index page code

---

Makefile
mediation_service/tests/performance/common/auth.py
mediation_service/tests/performance/locustfile.py

Also added an option to a handle and retry failed requests to get a better average of successful requests when testing.

AMB-989: Modified test to hit Mediation Service endpoint without going through the demo client
